fixes:
  - "ballerina/np/**/::../ballerina/"
  - "io/ballerina/lib/np/compilerplugin/::./compiler-plugin/src/main/java/io/ballerina/lib/np/compilerplugin/"

ignore:
  - "ballerina-tests"
  - "examples"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
