[plugin]
id = "ai.np-compiler-plugin"
class = "io.ballerina.lib.ai.np.compilerplugin.CompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.np-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-@ballerinaToOpenApiVersion.version@.jar"

