[package]
org = "ballerina"
name = "np"
version = "0.3.1"
authors = ["Ballerina"]
keywords = ["natural programming", "ai"]
repository = "https://github.com/ballerina-platform/module-ballerina-np"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "np-native"
version = "0.3.1"
path = "../native/build/libs/np-native-0.3.1-SNAPSHOT.jar"

[[dependency]]
org="ballerina"
name="ai"
version="1.0.0"
repository="local"
