[package]
org = "ballerina"
name = "np_tests"
version = "0.3.1"

[[dependency]]
org = "ballerina"
name = "np_test_commons"
repository = "local"
version = "0.3.1"

[[dependency]]
org="ballerina"
name="ai"
version="1.0.1"
repository="local"
